### ISSUE TITLE
Geonames feature simple importer error

### ISSUE THREAD

**Issue by QuestofIranon** [gisgraphy/gisgraphy#1]
I've been trying to import the data on a server, everytime it reaches this step I get the error:

Error : An error occurred when processing GeonamesFeatureSimpleImporter : Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: JDBC rollback failed

I'm running the 4.0-beta1 distribution available at http://www.gisgraphy.com/download/index.htm
on Ubuntu 12.10 (unfortunately, circumstances prevent me from upgrading this server) using Oracle java 1.7, postgres 9.1 and postgis1.5
I'm only importing Australian data files.

I've included the end of the gisgraphy-importer.log file output regarding the error.

`
[ERROR] [com.gisgraphy.importer.AbstractSimpleImporterProcessor] [09 Oct 2015 04:15:30,124] (importBackgroundThread,) : An error occurred when processing Ge$
org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionExceptio$
        at org.springframework.orm.hibernate3.HibernateTransactionManager.doRollback(HibernateTransactionManager.java:680)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:846)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:823)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.rollbackTransaction(AbstractSimpleImporterProcessor.java:417)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporterProcessor.java:397)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.process(AbstractSimpleImporterProcessor.java:304)
        at com.gisgraphy.importer.ImporterManager.importAll(ImporterManager.java:118)
        at com.gisgraphy.webapp.action.ImportAction.doImport(ImportAction.java:93)
        at com.gisgraphy.webapp.action.ImportAction.execute(ImportAction.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:441)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:280)
        at org.apache.struts2.interceptor.BackgroundProcess$1.run(BackgroundProcess.java:57)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.TransactionException: JDBC rollback failed
        at org.hibernate.transaction.JDBCTransaction.rollback(JDBCTransaction.java:170)
        at org.springframework.orm.hibernate3.HibernateTransactionManager.doRollback(HibernateTransactionManager.java:677)
        ... 16 more
Caused by: org.postgresql.util.PSQLException: An I/O error occured while sending to the backend.
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:214)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.executeTransactionCommand(AbstractJdbc2Connection.java:617)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.rollback(AbstractJdbc2Connection.java:654)
        at org.apache.commons.dbcp.DelegatingConnection.rollback(DelegatingConnection.java:328)
        at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.rollback(PoolingDataSource.java:312)
        at org.hibernate.transaction.JDBCTransaction.rollbackAndResetAutoCommit(JDBCTransaction.java:183)
        at org.hibernate.transaction.JDBCTransaction.rollback(JDBCTransaction.java:162)
        ... 17 more
Caused by: java.io.IOException: Stream closed
        at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at org.postgresql.core.PGStream.flush(PGStream.java:531)
        at org.postgresql.core.v3.QueryExecutorImpl.sendSync(QueryExecutorImpl.java:672)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:187)
        ... 23 more
[INFO] [com.gisgraphy.importer.ImporterManager] [09 Oct 2015 04:15:34,348] (importBackgroundThread,) : re-enabling stats
[INFO] [com.gisgraphy.importer.ImporterManager] [09 Oct 2015 04:15:34,348] (importBackgroundThread,) : re-enabling stats
`

**Comment by gisgraphy** [comment]
It seems to be a network problem (or postgres one, but don't think it is a bug in Gisgraphy) : Stream closed

Do you use a firewall, do you use replication ?

If not (postgres is on the same server), can you try this :

http://stackoverflow.com/questions/20878854/postgresql-exception-org-postgresql-util-psqlexception-an-i-o-error-occured-w

**Comment by QuestofIranon** [comment]
Postgres is running on the same server, I checked the postgresql.config file and `synchronous_standby_names = '*'` was already commented out.

**Comment by gisgraphy** [comment]
I can not reproduce the problem but I have already seen that on an other project and it was using jetty and postgres :

First : some questions :
Have you try to reset and re run the import ?
if so, Is it always at the same step /percent that it fails.

second : suggestions :
Try with tomcat
change the jdbc file with a more appropriate version (depends on your postgres version) : https://jdbc.postgresql.org/download.html

finally : some explanations:
This is very strange that this error appears because the importer have a special functionnalities that retry on errors 5 times. see RetryOnErrorTemplate class. So the problem seems to be a real one that occurred several times, not only one

Hope it helps... and let me know

**Comment by QuestofIranon** [comment]
I've reset and re run the import at least 10 times. I tried recreating the database between trying imports as well. It always crashes during the first file it tries to import into the database (after the download/ file check). It doesn't just fail (the first few times it did just fail) The process becomes unresponsive and no longer serves the pages now.

I'll try the other suggestions tonight.
Just for reference, this is my current error (truncated):

`
WARN [btpool0-3] UserSuppliedConnectionProvider | No connection properties specified - the user must supply JDBC connections
ERROR [btpool0-3] SchemaExport | schema export unsuccessful
java.lang.UnsupportedOperationException: The user must supply a JDBC connection
        at org.hibernate.connection.UserSuppliedConnectionProvider.getConnection(UserSuppliedConnectionProvider.java:30)
        [..]
        at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)
`

And my jdbc.properties file:
`
jdbc.driverClassName=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost/gisgraphy
jdbc.username=[ommitted]
jdbc.password=[ommitted]

hibernate.dialect=org.hibernatespatial.postgis.PostgisDialectNG

# Needed by Hibernate3 Maven Plugin defined in pom.xml
hibernate.connection.username=[ommitted]
hibernate.connection.password=[ommitted]
hibernate.connection.url=jdbc:postgresql://localhost/gisgraphy
hibernate.connection.driver_class=org.postgresql.Driver
`

**Comment by gisgraphy** [comment]
please retry with the new v 5.0. it should be ok
