### ISSUE TITLE
Change port from 8080

### ISSUE THREAD

**Issue by gyscos** [gisgraphy/gisgraphy#10]
I am following the instructions at http://www.gisgraphy.com/documentation/installation/installgisgraphy.htm.

However, I cannot find how to change the port from the default 8080. I tried modifying `etc/jetty.xml`:

```
    <Call name="addConnector">
      <Arg>
          <New class="org.mortbay.jetty.bio.SocketConnector">
            <Set name="port">8080</Set>
            <Set name="maxIdleTime">50000</Set>
            <Set name="lowResourceMaxIdleTime">1500</Set>
          </New>
      </Arg>
    </Call>
```
and replaced the `8080` with `8765`, but it doesn't seem to change anything, and I still get the following error as I already have another service listening on 8080:

```
2016-09-21 17:49:21.971::WARN:  failed SocketConnector @ 0.0.0.0:8080
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:181)
	at org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:78)
	at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:72)
	at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:252)
	at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:145)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
	at org.mortbay.jetty.Server.doStart(Server.java:221)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
	at org.mortbay.xml.XmlConfiguration.main(XmlConfiguration.java:929)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mortbay.start.Main.invokeMain(Main.java:183)
	at org.mortbay.start.Main.start(Main.java:497)
	at org.mortbay.start.Main.main(Main.java:115)
```

Is there a way to change the port gisgraphy uses? Thanks!

**Comment by gisgraphy** [comment]
Hi

you can find some informations here : 
http://gisgraphy.com/forum/viewtopic.php?f=3&t=10430&sid=1939460bc26224b205dd708440d3f1f6 
but you seems to have done the correct changes.

David

**Comment by gyscos** [comment]
Aah, the `run/gisgraphy.pid` file was left behind, so running `./launch.sh` was not actually trying anything, just printing the old log file.
