### ISSUE TITLE
An error occurred when processing GeonamesCountryImporter

### ISSUE THREAD

**Issue by gruevyhat** [gisgraphy/gisgraphy#36]
I've tried to import the data several times, now, and in each case, I get an error like the following:

    Error : An error occurred when processing GeonamesCountryImporter : An error occurred when processing countryInfo.txt : An Error occurred on Line 1 for AD	AND	020	AN	Andorra	Andorra la Vella	468	84000	EU	.ad	EUR	Euro	376	AD###	^(?:AD)*(\d{3})$	ca	3041565	ES,FR	: IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm; nested exception is org.hibernate.PropertyAccessException: IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm

The full log output is below. Any help would be greatly appreciated!

    [ERROR] [com.gisgraphy.importer.AbstractSimpleImporterProcessor] [19 Jun 2018 22:38:21,389] (importBackgroundThread,) : An error occurred when processing GeonamesCountryImporter : An error occurred when processing countryInfo.txt : An Error occurred on Line 1 for AD      AND     020       AN      Andorra Andorra la Vella        468     84000   EU      .ad     EUR     Euro    376     AD###   ^(?:AD)*(\d{3})$        ca      3041565 ES,FR    : IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm; nested exception is org.hibernate.PropertyAccessException: IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm
    com.gisgraphy.importer.ImporterException: An error occurred when processing countryInfo.txt : An Error occurred on Line 1 for AD        AND     020     AN      Andorra Andorra la Vella        468     84000   EU      .ad     EUR     Euro    376     AD###   ^(?:AD)*(\d{3})$        ca
    	3041565 ES,FR    : IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm; nested exception is org.hibernate.PropertyAccessException: IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm
    	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporterProcessor.java:422)
    	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.process(AbstractSimpleImporterProcessor.java:306)
    	at com.gisgraphy.importer.ImporterManager.importAll(ImporterManager.java:138)
    	at com.gisgraphy.webapp.action.ImportAction.doImport(ImportAction.java:130)
    	at com.gisgraphy.webapp.action.ImportAction.execute(ImportAction.java:165)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:441)
    	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:280)
    	at org.apache.struts2.interceptor.BackgroundProcess$1.run(BackgroundProcess.java:57)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: org.springframework.orm.hibernate3.HibernateSystemException: IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm; nested exception is org.hibernate.PropertyAccessException: IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm
    	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:709)
    	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:416)
    	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:416)
    	at org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:379)
    	at org.springframework.orm.hibernate3.HibernateTemplate.saveOrUpdate(HibernateTemplate.java:782)
    	at com.gisgraphy.domain.repository.GenericDao.save(GenericDao.java:112)
    	at com.gisgraphy.domain.repository.GenericGisDao.save(GenericGisDao.java:424)
    	at com.gisgraphy.domain.repository.CountryDao.save(CountryDao.java:72)
    	at com.gisgraphy.domain.repository.CountryDao.save(CountryDao.java:46)
    	at com.gisgraphy.importer.GeonamesCountryImporter.processData(GeonamesCountryImporter.java:162)
    	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.readLineAndProcessData(AbstractSimpleImporterProcessor.java:235)
    	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporterProcessor.java:402)
    	... 12 more
    Caused by: org.hibernate.PropertyAccessException: IllegalArgumentException occurred while calling setter of com.gisgraphy.domain.geoloc.entity.GisFeature.adm
    	at org.hibernate.property.BasicPropertyAccessor$BasicSetter.set(BasicPropertyAccessor.java:128)
    	at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:583)
    	at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:229)
    	at org.hibernate.persister.entity.AbstractEntityPersister.setPropertyValues(AbstractEntityPersister.java:3847)
    	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:299)
    	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:203)
    	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:143)
    	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:210)
    	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:195)
    	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:117)
    	at org.hibernate.event.def.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:93)
    	at org.hibernate.impl.SessionImpl.fireSaveOrUpdate(SessionImpl.java:685)
    	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:677)
    	at org.hibernate.impl.SessionImpl.saveOrUpdate(SessionImpl.java:673)
    	at org.springframework.orm.hibernate3.HibernateTemplate$16.doInHibernate(HibernateTemplate.java:786)
    	at org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:411)
    	... 21 more
    Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@283c5f35
    	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.hibernate.property.BasicPropertyAccessor$BasicSetter.set(BasicPropertyAccessor.java:66)
    	... 36 more
    [INFO] [com.gisgraphy.importer.ImporterManager] [19 Jun 2018 22:38:21,429] (importBackgroundThread,) : re-enabling stats
    [ERROR] [com.gisgraphy.importer.ImporterHelper] [19 Jun 2018 22:38:21,430] (importBackgroundThread,) : can not call a null URL

**Comment by ant-tony-antony** [comment]
Replacing the following files by their updated version will fix the problem. You can find these files under webapps/ROOT/WEB-INF/lib/... folder. 

spring-beans-4.3.5.RELEASE.jar
spring-core-4.3.5.RELEASE.jar
spring-jcl-4.3.5.RELEASE.jar
spring-jdbc-4.3.5.RELEASE.jar
spring-tx-4.3.5.RELEASE.jar
postgresql-8.1-407.jdbc3.jar

Updated Versions:

spring-beans-5.0.4.RELEASE.jar
spring-core-5.0.4.RELEASE.jar
spring-jcl-5.0.4.RELEASE.jar
spring-jdbc-5.0.4.RELEASE.jar
spring-tx-5.0.4.RELEASE.jar
postgresql-42.2.2.jar
