### ISSUE TITLE
database update

### ISSUE THREAD

**Issue by Inaso89** [gisgraphy/gisgraphy#47]
hello,
highly admire ur work! how incredible!
I want to clarify a point if you allow me. if I hosted Gisgraphy server and imported some specific country database, does this database update periodically?  I need the data to update periodically. does Gisgraphy support that? 
thank you in advance

**Comment by gisgraphy** [comment]
hi


the updates frequency is not defined. Each time a new import is done, a 
new dataset is available to be import. nothing is automatic. you have to 
re import the data from scratch.


we ofcource provide dump in CSV or SQL format that can be inject without 
doing the import.

for instance we will add a new dataset that will add US data and we will 
be near 100 % of coverage. we will do a new dump then.

You don't have to buy the whole dataset again.

the dump will contains all the data but you only pay the updates :
- suppose you buy the all countries dump of 500 millions of addresses,
- then there is, for instance,  an update in january with 10 millions 
addresses added=> if you buy the updates you will only pay 10 000 000 * 
0.0001€ = 1000 €
- then , suppose in June we add 5 000 000 addresses more, you will pay 5 
000 000* 0.0001 =500 €

if you dont buy the one in january, but in june, you will pay 1500€ 
because there is 15 000 000 addresses added compare to your last buy.

so you buy when you want, and you only pay the updates. even if the dump 
will contains old and new data.

Actually there is no frequency defined since we focus on bug fix and new 
importer but in 2019, we plan to do  updates every 6 months first and 
then every 3/4 months in end of 2019



Actually there is no frequency defined since we focus on bug fix and new 
importer but in 2019, we plan to do  updates every 6 months first and 
then every 3/4 months in end of 2019

Le 14/05/2019 à 20:33, Inaso89 a écrit :

**Comment by Inaso89** [comment]
so you mean that if I want to update the data, I have a choice of tow: 
1. I import the data again for free, and get an updated dataset.
2. you can inject the updated data into my database without the need of re-importing and that will be paid.

**Comment by gisgraphy** [comment]
HiYes. You are right. Inject the data in the database (point number 2) is done by you. I provide a dump with the instructions You can do a quote at https://premium.gisgraphy.com/consult/datasets/purchaseformDavid Masclet-------- Message original --------Objet : Re: [gisgraphy/gisgraphy] database update (#47)De : Inaso89 À : gisgraphy/gisgraphy Cc : gisgraphy ,Comment so you mean that if I want to update the data, I have a choice of tow:

I import the data again for free, and get an updated dataset.
you can inject the updated data into my database without the need of re-importing and that will be paid.


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gisgraphy/gisgraphy/issues/47?email_source=notifications\u0026email_token=AB2LKSEEUAISD3AB2TUQXV3PWBL4HA5CNFSM4HM4SED2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVWUYRA#issuecomment-493702212",
"url": "https://github.com/gisgraphy/gisgraphy/issues/47?email_source=notifications\u0026email_token=AB2LKSEEUAISD3AB2TUQXV3PWBL4HA5CNFSM4HM4SED2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVWUYRA#issuecomment-493702212",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Inaso89** [comment]
thank you so much for your quick response. highly appreciate :)

**Comment by Inaso89** [comment]
hello again,
am trying to host Gisgraphy locally.I want to import data for only three countries.  when I run the importer it's giving the NullPointerException as follows:
`[ERROR] [com.gisgraphy.importer.AbstractSimpleImporterProcessor] [22 May 2019 12:45:29,541] (importBackgroundThread,) : An error occurred when processing GeonamesLanguageImporter : null
java.lang.NullPointerException
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:824)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.rollbackTransaction(AbstractSimpleImporterProcessor.java:439)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporterProcessor.java:419)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.process(AbstractSimpleImporterProcessor.java:306)
        at com.gisgraphy.importer.ImporterManager.importAll(ImporterManager.java:138)
        at com.gisgraphy.webapp.action.ImportAction.doImport(ImportAction.java:130)
        at com.gisgraphy.webapp.action.ImportAction.execute(ImportAction.java:165)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:441)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:280)
        at org.apache.struts2.interceptor.BackgroundProcess$1.run(BackgroundProcess.java:57)
        at java.lang.Thread.run(Thread.java:748)
[INFO] [com.gisgraphy.importer.ImporterManager] [22 May 2019 12:45:29,542] (importBackgroundThread,) : re-enabling stats
[ERROR] [com.gisgraphy.importer.ImporterHelper] [22 May 2019 12:45:29,573] (importBackgroundThread,) : Can not determine HTTP file size of http://download.geonames.org/export/zip/OM.zip because it does not exists (404)
[ERROR] [com.gisgraphy.importer.ImporterHelper] [22 May 2019 12:45:29,589] (importBackgroundThread,) : Can not determine HTTP file size of http://download.geonames.org/export/zip/SA.zip because it does not exists (404)
[ERROR] [com.gisgraphy.importer.ImporterHelper] [22 May 2019 12:45:29,605] (importBackgroundThread,) : Can not determine HTTP file size of http://download.geonames.org/export/zip/AE.zip because it does not exists (404)
[ERROR] [com.gisgraphy.importer.ImporterHelper] [22 May 2019 12:45:29,607] (importBackgroundThread,) : can not call a null URL
`
I tried to re-import the data excluding the Geonames data but it's still not working. any advice ?
thank you in advance

![image](https://user-images.githubusercontent.com/37980585/58175936-ebdda700-7ca9-11e9-83ad-a3e5361a3c6b.png)

**Comment by Inaso89** [comment]
I passed this problem with the aid of issue #27 .

**Comment by Inaso89** [comment]
but I need to make make sure of the update issue. excuse me for bothering you again with the same issue.
 actually, i am interested in buying the SA, EA, and OM data-sets. in addition, i need to update it, let's say every month. could you please clarify these points for me:
1. every time there is an update I have to pay for it? it's not like a lifetime update "pay for it once and get it for the life time" 
2. in this case, I will pay for the updates per lines or per addresses?  for instance, if there is only 100 new lines in the updated data how much will it cost?
3. I've read once that there is an update for the OpenStreetMap data every week!! that means you have an updated data every week ? so for sure I will find an updated data every month for example?
thank you in advance for your time 
Inas
