### ISSUE TITLE
 Error while importing Brazil data

### ISSUE THREAD

**Issue by smsoousa** [gisgraphy/gisgraphy#51]
Hello, first of all congratulations on your excellent work with Gisgraphy. After some time trying, I was able to install Gisgraphy, but I get an error while importing the data:

**Error : An error occurred when processing OpenStreetMapCitiesSimpleImporter : An error occurred when processing BR.txt : An Error occurred on Line 59180 for N	5973095039	Jardim Santos Dumont ||	BR 0101000020E61000005A4A969350F348C0BE59396A3BF836C0	suburb	São Paulo___4___298204___Ourinhos___8___298375___Região Sudeste___3___3073228___Mesorregião de Assis___5___4781870___Microrregião de Ourinhos___7___4781880___Ourinhos___9___5684923	"" : Error executing query**

I've tried reinstalling and importing a few times, but it seems that the error always appears in this same percentage of the process. 

And I get this output on my SSH terminal:

`return new ZIPValinho
return new ZIPPytiontouta  Ex-J.R. Paniagua
return new ZIPCR Almeida
return new ZIPVila Romi
return new ZIPCutucum
return new ZIPParque Brasília
return new ZIPVillage do Cerrado
return new ZIPCarlos Germano Naumann
return new ZIPSol Nascente
return new ZIPRibeira
return new ZIPJardim Itapark
return new ZIPLinha Quilombo
return new ZIPSerra Velha
return new ZIPCondomínio Villagos
return new ZIPCerro da Fumaça
return new ZIPLapinha Nova
return new ZIPArroio do Ouro
return new ZIPJardim Santos Dumont ||
Aug 17, 2019 4:54:12 AM org.apache.solr.common.SolrException log
SEVERE: org.apache.solr.common.SolrException
        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:134)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:165)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1376)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:365)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:260)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1089)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:365)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:712)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:2                                                                                    11)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
        at org.mortbay.jetty.Server.handle(Server.java:285)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:502)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:821)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:513)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:208)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:378)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:226)
        at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:442)
Caused by: org.apache.lucene.queryParser.ParseException: Cannot parse '_query_:"{!edismax qf='label^                                                                                    15 name^25 all_name^10 fully_qualified_name  all_adm1_name^0.2 all_adm2_name^0.2 ' pf='all_label' ps                                                                                    =0 tie='0.1' bq=' placetype:city^200'   mm='2<2'  bf='recip(geodist(),0.5,20000,1)'}Jardim Santos Du                                                                                    mont ||"': Cannot parse 'Jardim Santos Dumont || ': Encountered "<EOF>" at line 1, column 24.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...

        at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:211)
        at org.apache.solr.search.LuceneQParser.parse(LuceneQParserPlugin.java:79)
        at org.apache.solr.search.QParser.getQuery(QParser.java:143)
        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:105)
        ... 22 more
Caused by: org.apache.lucene.queryParser.ParseException: Cannot parse 'Jardim Santos Dumont || ': En                                                                                    countered "<EOF>" at line 1, column 24.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...

        at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:211)
        at org.apache.solr.search.ExtendedDismaxQParser.parse(ExtendedDismaxQParserPlugin.java:295)
        at org.apache.solr.search.QParser.getQuery(QParser.java:143)
        at org.apache.solr.search.SolrQueryParser.getFieldQuery(SolrQueryParser.java:191)
        at org.apache.lucene.queryParser.QueryParser.getFieldQuery(QueryParser.java:752)
        at org.apache.lucene.queryParser.QueryParser.Term(QueryParser.java:1580)
        at org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1317)
        at org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1245)
        at org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1234)
        at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:206)
        ... 25 more
Caused by: org.apache.lucene.queryParser.ParseException: Encountered "<EOF>" at line 1, column 24.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...

        at org.apache.lucene.queryParser.QueryParser.generateParseException(QueryParser.java:1842)
        at org.apache.lucene.queryParser.QueryParser.jj_consume_token(QueryParser.java:1724)
        at org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1335)
        at org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1274)
        at org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1234)
        at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:206)
        ... 34 more

[ERROR] [com.gisgraphy.importer.AbstractSimpleImporterProcessor] [17 Aug 2019 04:54:12,656] (importB                                                                                    ackgroundThread,) : An error occurred when processing OpenStreetMapCitiesSimpleImporter : An error o                                                                                    ccurred when processing BR.txt : An Error occurred on Line 59180 for N  5973095039              Jard                                                                                    im Santos Dumont ||     BR                                      0101000020E61000005A4A969350F348C0BE                                                                                    59396A3BF836C0                  suburb          São Paulo___4___298204___Ourinhos___8___298375___Reg                                                                                    ião Sudeste___3___3073228___Mesorregião de Assis___5___4781870___Microrregião de Ourinhos___7___4781                                                                                    880___Ourinhos___9___5684923    "" : Error executing query
com.gisgraphy.importer.ImporterException: An error occurred when processing BR.txt : An Error occurr                                                                                    ed on Line 59180 for N  5973095039              Jardim Santos Dumont || BR                         0                                                                                    101000020E61000005A4A969350F348C0BE59396A3BF836C0                       suburb          São Paulo___                                                                                    4___298204___Ourinhos___8___298375___Região Sudeste___3___3073228___Mesorregião de Assis___5___47818                                                                                    70___Microrregião de Ourinhos___7___4781880___Ourinhos___9___5684923    "" : Error executing query
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporter                                                                                    Processor.java:422)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.process(AbstractSimpleImporterProc                                                                                    essor.java:306)
        at com.gisgraphy.importer.ImporterManager.importAll(ImporterManager.java:138)
        at com.gisgraphy.webapp.action.ImportAction.doImport(ImportAction.java:130)
        at com.gisgraphy.webapp.action.ImportAction.execute(ImportAction.java:165)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java                                                                                    :441)
        at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.                                                                                    java:280)
        at org.apache.struts2.interceptor.BackgroundProcess$1.run(BackgroundProcess.java:57)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.gisgraphy.fulltext.FullTextSearchException: Error executing query
        at com.gisgraphy.fulltext.FullTextSearchEngine.executeQuery(FullTextSearchEngine.java:473)
        at com.gisgraphy.importer.OpenStreetMapCitiesSimpleImporter.getNearestByPlaceType(OpenStreet                                                                                    MapCitiesSimpleImporter.java:626)
        at com.gisgraphy.importer.OpenStreetMapCitiesSimpleImporter.processData(OpenStreetMapCitiesS                                                                                    impleImporter.java:261)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.readLineAndProcessData(AbstractSim                                                                                    pleImporterProcessor.java:235)
        at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporter                                                                                    Processor.java:402)
        ... 12 more
Caused by: org.apache.solr.client.solrj.SolrServerException: Error executing query
        at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:95)
        at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:311)
        at com.gisgraphy.fulltext.FullTextSearchEngine.executeQuery(FullTextSearchEngine.java:471)
        ... 16 more
Caused by: org.apache.solr.common.SolrException: null

null

request: http://localhost:8080/solr/select?indent=off&echoParams=none&start=0&rows=1&wt=javabin&fl=s                                                                                    core,feature_id,name,fully_qualified_name,zipcode,lat,lng,lat_admin_centre,lng_admin_centre,placetyp                                                                                    e,country_code,country_name,one_way,length,street_type,street_ref,openstreetmap_id,feature_class,fea                                                                                    ture_code,population,name_ascii,timezone,elevation,continent,currency_code,currency_name,fips_code,i                                                                                    soalpha2_country_code,isoalpha3_country_code,postal_code_mask,postal_code_regex,phone_prefix,spoken_                                                                                    languages,tld,capital_name,area,is_in,is_in_place,is_in_adm,is_in_zip,house_numbers,amenity,municipa                                                                                    lity,label,label_postal,toll,surface,lanes,azimuth_end,azimuth_start,municipality,max_speed,speed_mo                                                                                    de,max_speed_backward,level,gtopo30,country_flag_url,google_map_url,yahoo_map_url,openstreetmap_map_                                                                                    url,adm1_name,adm2_name,adm3_name,adm4_name,adm5_name,adm1_code,adm2_code,adm3_code,adm4_code,adm5_c                                                                                    ode,label_alternate,name_alternate&sfield=location&pt=-22.9696566,-49.9008965&fq={!bbox sfield=locat                                                                                    ion}&fq=country_code:BR&fq=placetype:(City OR CitySubdivision)&d=10.0&qt=advanced&q=_query_:"{!edism                                                                                    ax qf='label^15 name^25 all_name^10 fully_qualified_name  all_adm1_name^0.2 all_adm2_name^0.2 ' pf='                                                                                    all_label' ps=0 tie='0.1' bq=' placetype:city^200'   mm='2<2'  bf='recip(geodist(),0.5,20000,1)'}Jar                                                                                    dim Santos Dumont ||"&wt=javabin&version=2
        at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.jav                                                                                    a:427)
        at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.jav                                                                                    a:249)
        at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:89)
        ... 18 more
[INFO] [com.gisgraphy.importer.ImporterManager] [17 Aug 2019 04:54:12,725] (importBackgroundThread,)                                                                                     : re-enabling stats
[ERROR] [com.gisgraphy.importer.ImporterHelper] [17 Aug 2019 04:54:12,726] (importBackgroundThread,)                                                                                     : can not call a null URL
 TokenHelper | Could not find token mapped to token name struts.token
WARN [btpool0-5] TokenHelper | Could not find token mapped to token name struts.token
`

If anyone can help me with this, I will be very grateful.

**Comment by smsoousa** [comment]
[http://104.237.10.26/error.jpg](url)

**Comment by lukazsj** [comment]
I have the same problem, anyone could help us?

**Comment by Inas-MA** [comment]
any update regarding this ?

**Comment by StAandrew** [comment]
Got the same error, any updates?

**Comment by gisgraphy** [comment]
Hi

I have updated the BR files on the server, please delete the one in data/import/openstreetmap/ and re run an import

**Comment by Inas-MA** [comment]
@gisgraphy I'm facing this with Ethiopia. could you please do the same for its files 😇
