### ISSUE TITLE
OpenStreetMap cities data import failing - An error occurred when processing ER.txt...

### ISSUE THREAD

**Issue by borice** [gisgraphy/gisgraphy#72]
Hello,

I am receiving an error when attempting to import some of the data, see below screenshot.
(I have tried this twice, both times the same error occurred)

Is there anything I can do to ignore the error and continue? Or fix it?

Thank you!
<img width="787" alt="Screen Shot 2021-07-09 at 11 21 00 AM" src="https://user-images.githubusercontent.com/431091/125108730-0cdefd00-e0a8-11eb-82a5-fae6631b1bd5.png">

**Comment by borice** [comment]
Here's the stack trace from the importer log...
```
[ERROR] [com.gisgraphy.importer.AbstractSimpleImporterProcessor] [09 Jul 2021 13:33:54,414] (importBackgroundThread,) : An error occurred when processing OpenStreetMapCitiesSimpleImporter : An error occurred when processing ER.txt : An Error occurred on Line 85 for N	1150903463		??????-??????	ER					0101000020E61000008065A549290C444064EE5A423E182D40			locality		""	"" : Error executing query
com.gisgraphy.importer.ImporterException: An error occurred when processing ER.txt : An Error occurred on Line 85 for N	1150903463		??????-??????	ER		0101000020E61000008065A549290C444064EE5A423E182D40			locality		""	"" : Error executing query
	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporterProcessor.java:422)
	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.process(AbstractSimpleImporterProcessor.java:306)
	at com.gisgraphy.importer.ImporterManager.importAll(ImporterManager.java:138)
	at com.gisgraphy.webapp.action.ImportAction.doImport(ImportAction.java:130)
	at com.gisgraphy.webapp.action.ImportAction.execute(ImportAction.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:441)
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:280)
	at org.apache.struts2.interceptor.BackgroundProcess$1.run(BackgroundProcess.java:57)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.gisgraphy.fulltext.FullTextSearchException: Error executing query
	at com.gisgraphy.fulltext.FullTextSearchEngine.executeQuery(FullTextSearchEngine.java:473)
	at com.gisgraphy.importer.OpenStreetMapCitiesSimpleImporter.getNearestByPlaceType(OpenStreetMapCitiesSimpleImporter.java:626)
	at com.gisgraphy.importer.OpenStreetMapCitiesSimpleImporter.processData(OpenStreetMapCitiesSimpleImporter.java:228)
	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.readLineAndProcessData(AbstractSimpleImporterProcessor.java:235)
	at com.gisgraphy.importer.AbstractSimpleImporterProcessor.processFile(AbstractSimpleImporterProcessor.java:402)
	... 12 more
Caused by: org.apache.solr.client.solrj.SolrServerException: Error executing query
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:95)
	at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:311)
	at com.gisgraphy.fulltext.FullTextSearchEngine.executeQuery(FullTextSearchEngine.java:471)
	... 16 more
Caused by: org.apache.solr.common.SolrException: null

null

request: http://localhost:8080/solr/select?indent=off&echoParams=none&start=0&rows=1&wt=javabin&fl=score,feature_id,name,fully_qualified_name,zipcode,lat,lng,lat_admin_centre,lng_admin_centre,placetype,country_code,country_name,one_way,length,street_type,street_ref,openstreetmap_id,feature_class,feature_code,population,name_ascii,timezone,elevation,continent,currency_code,currency_name,fips_code,isoalpha2_country_code,isoalpha3_country_code,postal_code_mask,postal_code_regex,phone_prefix,spoken_languages,tld,capital_name,area,is_in,is_in_place,is_in_adm,is_in_zip,house_numbers,amenity,municipality,label,label_postal,toll,surface,lanes,azimuth_end,azimuth_start,municipality,max_speed,speed_mode,max_speed_backward,level,gtopo30,country_flag_url,google_map_url,yahoo_map_url,openstreetmap_map_url,adm1_name,adm2_name,adm3_name,adm4_name,adm5_name,adm1_code,adm2_code,adm3_code,adm4_code,adm5_code,label_alternate,name_alternate&sfield=location&pt=14.547350000000002,40.09501&fq={!bbox sfield=location}&fq=country_code:ER&fq=placetype:(City OR CitySubdivision)&d=10.0&qt=advanced&q=_query_:"{!edismax qf='label^15 name^25 all_name^10 fully_qualified_name  all_adm1_name^0.2 all_adm2_name^0.2 ' pf='all_label' ps=0 tie='0.1' bq=' '   mm='2<2'  bf='recip(geodist(),0.5,20000,1)'}-"&wt=javabin&version=2
	at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:427)
	at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:249)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:89)
	... 18 more
```

**Comment by gisgraphy** [comment]
hi,

this error occurs when a transaction is not done correctly, I have 
already put a piece of code to avoid that but some errors still throws,

unfortunately, you must reset and relaunch, the next version , will 
restart automatically

regards

**Comment by borice** [comment]
Thank you for responding, but I'm not sure I understand.  Are you saying to just re-try the importing?  I already did this twice and both times it failed in the same place.  Is there a new release of gisgraphy that I can use that has the updated code you mentioned?

**Comment by gisgraphy** [comment]
HiThe last version is available at http://download.gisgraphy.com/snapshots/For information, i have test those files and it was ok for me. If it still fails, just tell me I will re upload the files

**Comment by borice** [comment]
Do you happen to have a Docker image built with the latest snapshot 5.0-beta3?

**Comment by borice** [comment]
Nevermind, I was able to build one. I can confirm that so far it's not crashing as before (however the import is still running...)  If it crashes again, I'll re-open this ticket.
